### ISSUE TITLE
Usar un nodo para crear el PBR

### ISSUE THREAD

**Issue by kone9** [oscurart/Blender-28-Addons#3]
Estoy mirando los tutoriales de como usar esta herramienta y me parece espectacular.
Sin embargo hay un problema a la hora bakear objetos; se hace confuso y poco intuitivo porque hay que tocar opciones desparramadas por todo el programa.
Una forma de solucionar este problema seria usando un nodo procedural.(Creo que se llama asi).

### Te paso una imagen que hice en GIMP.
![oscurart](https://user-images.githubusercontent.com/12847027/53733726-a9ea5500-3e60-11e9-84a2-22edfe6b05f9.jpg)

**Comment by oscurart** [comment]
Hola Ari.
Hay muchas cosas que te van a saltar en la practica... y por eso el bake PBR usa la MISMA idea que el Bake de blender.

El margen por ejemplo está en el margen del Bake común, no hace falta tener repetido el espacio.

Con respecto a los presets, es imposible proveer presets hardcodeados para cada programa. Es más interesante darte los mapas y que vos con el compositor te armés un arbol y exporte, toma 5 minutos y te da mas flexibiliadd.

Con respecto a setear el HR como el LR, vas a encontrar conflictos.
En primer lugar si seteas un HR me estás diciendo que solo tendrias 1 solo hr, y esto funciona con muuchos objetos y el LR como el active Object.

La forma de pensar es la misma que la del bake común!

**Comment by kone9** [comment]
> 
> 
> Hola Ari.
> Hay muchas cosas que te van a saltar en la practica... y por eso el bake PBR usa la MISMA idea que el Bake de blender.
> 
> El margen por ejemplo está en el margen del Bake común, no hace falta tener repetido el espacio.
> 
> Con respecto a los presets, es imposible proveer presets hardcodeados para cada programa. Es más interesante darte los mapas y que vos con el compositor te armés un arbol y exporte, toma 5 minutos y te da mas flexibiliadd.
> 
> Con respecto a setear el HR como el LR, vas a encontrar conflictos.
> En primer lugar si seteas un HR me estás diciendo que solo tendrias 1 solo hr, y esto funciona con muuchos objetos y el LR como el active Object.
> 
> La forma de pensar es la misma que la del bake común!
