### ISSUE TITLE
Bake PBR Color Management muted the color in PNG

### ISSUE THREAD

**Issue by enzyme69** [oscurart/Blender-28-Addons#5]
Not sure if I am doing this incorrectly, or maybe the EXR to PNG conversion muted the color. 

But you can see here the wood x metal color from original (LEFT) when baked out as (RIGHT)

<img width="1557" alt="Screen Shot 2020-08-01 at 12 41 22 pm" src="https://user-images.githubusercontent.com/3952687/89092352-60ef5500-d3f4-11ea-8ac3-b3ff10d0fe51.png">

**Comment by enzyme69** [comment]
<img width="855" alt="Screen Shot 2020-08-01 at 12 49 28 pm" src="https://user-images.githubusercontent.com/3952687/89092476-72852c80-d3f5-11ea-9c82-d7d78605bd31.png">

Preview seems correct, but when brought into Blender or as AR object, it become darker or blown up or muted ... wonder why. Is this EXR to PNG issue?

**Comment by enzyme69** [comment]
If you have time, could try this wood material, mixing with your other PBR material, baking it out as PNG, but keeping the same color and look of the wood, before and after baking:

[Bamboo.zip](https://github.com/oscurart/Blender-28-Addons/files/5009750/Bamboo.zip)

**Comment by enzyme69** [comment]
When I load the texture as EXR, the color seems correct~

**Comment by enzyme69** [comment]
EXR texture loaded correctly so it must be the PNG that's wrong.

<img width="619" alt="Screen Shot 2020-08-01 at 1 19 31 pm" src="https://user-images.githubusercontent.com/3952687/89092971-a5c9ba80-d3f9-11ea-9e47-4a067d12b33b.png">

**Comment by oscurart** [comment]
@enzyme69  
Your problem is how you load the profiles.
All exr textures are LINEAR <<<<<<<<<<<<<<<
The pngs can be sRGB or NonColor . The base color and subsurface are sRGB,  only this maps! the others are Linear.
