### ISSUE TITLE
Mesh Cache Tools can't activate if  Display addon information and preferences are shown

### ISSUE THREAD

**Issue by kintuX** [oscurart/Blender-28-Addons#7]
Trying to activate addon with display information open, following error occurs:
![broken](https://user-images.githubusercontent.com/61623470/103144322-d05d3c80-4727-11eb-8426-7ebaef71601b.jpg)

`Traceback (most recent call last):
  File "C:\programi\b291\2.91\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "C:\Users\309\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\oscurart_mesh_cache_tools.py", line 353, in register
    bpy.utils.register_class(OscurartMeshCacheSceneAutoLoad)
ValueError: register_class(...): already registered as a subclass 'OscurartMeshCacheSceneAutoLoad'
`

With display information closed, addon activates OK.
![activeOK](https://user-images.githubusercontent.com/61623470/103144329-0ac6d980-4728-11eb-8aad-336de098451d.jpg)

Blender 2.91, OS: W-10

**Comment by oscurart** [comment]
Hi! 
Are you using the autoload?

**Comment by kintuX** [comment]
Autoload? If you mean "Auto Run Python Scripts", then No, I have it disabled.

**Comment by oscurart** [comment]
I'm installing it. I haven't problems.
The problem is when you unregister the addon. 
![Peek 2020-12-27 11-32](https://user-images.githubusercontent.com/15130162/103173097-469c9480-4837-11eb-90db-f349f74d2be7.gif)
